# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MyApp' do



source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'MBProgressHUD', '~> 0.9.1'

pod 'Alamofire', '~> 4.0'


pod 'MMDrawerController', '~> 0.5.7'

pod 'SDWebImage'


pod 'UIActivityIndicator-for-SDWebImage'

pod 'SnapKit', '~> 3.0.2'


pod "FBSDKCoreKit"

pod "FBSDKShareKit" 

pod "FBSDKLoginKit"


pod 'SBPickerSelector'

pod 'Firebase/Core'
pod 'Firebase/Crash'


pod 'SwiftDate', '~> 4.0'
pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

end


